config/routes.rb
Resume::Application.routes.draw do
  resources :documents

   root :to => "documents#current"

end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController


  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @documents }
    end
  end



  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @document }
    end
  end


  def current
    @document = Document.last
    respond_to do |format|
      format.html { render action:'show' } 
      format.xml  { render :xml => @document }
    end
  end

#  def new
#    @document = Document.new
#
#    respond_to do |format|
#      format.html # new.html.erb
#      format.xml  { render :xml => @document }
#    end
#  end


  #def edit
  #  @document = Document.find(params[:id])
  #end



  #def create
  #  @document = Document.new(params[:document])

  #  respond_to do |format|
  #    if @document.save
  #      format.html { redirect_to(@document, :notice => 'Document was successfully created.') }
  #      format.xml  { render :xml => @document, :status => :created, :location => @document }
  #    else
  #      format.html { render :action => "new" }
  #      format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
  #    end
  #  end
  #end



  #def update
  #  @document = Document.find(params[:id])
#
 #   respond_to do |format|
 #     if @document.update_attributes(params[:document])
#        format.html { redirect_to(@document, :notice => 'Document was successfully updated.') }
#        format.xml  { head :ok }
#      else
#        format.html { render :action => "edit" }
#        format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
#      end
#    end
#  end
#
#
#
#  def destroy
#    @document = Document.find(params[:id])
#    @document.destroy
#
#    respond_to do |format|
#      format.html { redirect_to(documents_url) }
#      format.xml  { head :ok }
#    end
#  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/_mobile_experience.html.erb
<div class='experience-section'>
  <h3>Mobile Experience:</h2>
  <ul>
    <li>
      Having no prior knowedge of C, C++ or Objective C; I built three iPhone applications making use of the iPhone's camera, location, data store and network communication APIs.  My last iPhone application, aMakeupMatchup, was inspired by rails.  Using Objective-C's meta programing capabilities, I built a very DRY application.  <%= link_to 'aMakeupMatchup', 'https://github.com/dapplebeforedawn/aMakeupMatchup' %> is available as open source on GitHub
    </li>
  </ul>
</div>

app/views/documents/_shipped_applications.html.erb
<div class='experience-section'>
  <h3>Shipped Applications:</h2>
  <ul>
    <li><%= link_to "MessagesOnAMission", 'http://build.messagesonamission.com' %>, a webservice that allows presentation viewers to text a message to the big screen. 
    <li><%= link_to "LuxeLedger", 'http://www.luxeledger.com' %>, a webservice to simplify the day-to-day operations of a boutique bridal store, or custom clothier.</li>
    <li><%= link_to "Schmozzel", 'http://schmozzel.com' %>, a group SMS replacement for GroupMe.</li>
    <li><%= link_to "iTryItOn", 'http://www.black-box-technology.com/itryiton/html/' %>, an iPhone application for the shopaholic you love.</li>
    <li><%= link_to "iDoStyle", 'http://www.dapplebeforedawn.com/iDoStyle/html/' %>, an iPhone application to help you design and share the look of your wedding party.</li>
    <li><%= link_to "aMakeupMatchup", 'http://itunes.apple.com/us/app/amakeupmatchup/id369575842?mt=8' %>, an open source iPhone application to help you remember style, shade and brand of your favorite cosmetics.</li>
  </ul>
</div>

app/views/documents/_work_and_education.html.erb
<div class='experience-section'>
  <h3>Work History and Education:</h2>
  <ul>
    <li>
      <strong>American Showa Inc. </strong><span>November 2005 to Present</span>
      <div class='work-summary'>
        Worked as the Test Group Team Leader, performing design and production validation testing
      </div>
    </li>
    <li>
      <strong>The Ohio State University</strong><span> June-2005</span>
      <div class='work-summary'>
        BS in Welding Engineering, 3.7 major GPA
      </div>
    </li>
    <li>
      <strong>Continuing Education</strong>
      <ul>
        <li>
          <%= link_to "Design and Analysis of Algorithms 1", "https://www.coursera.org/course/algo" %> <span>Spring 2012</span>
          <div class='work-summary'>
            Scored 97 of 100 possible points
          </div>
        </li>
        <li>
          <%= link_to "Machine Learning", "https://www.coursera.org/course/ml"%> <span>Spring 2012</span>
          <div class='work-summary'>
            Scored 830 of 780 possible points
          </div>
        </li>
      </ul>
      <div class='work-summary'>
      </div>
    </li>
  </ul>
</div>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= link_to 'Show', document %></td>
    <td><%= link_to 'Edit', edit_document_path(document) %></td>
    <td><%= link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<div id='document'>
  
  <div itemscope itemtype="http://schema.org/Person">
    <h1 itemprop="name">Mark J. Lorenz</h1>
    <!--<img src="janedoe.jpg" itemprop="image" />-->

    <div class='contact'>
      <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
        <span itemprop="streetAddress">1756 Darrow Dr.</span>
        <span itemprop="addressLocality">Powell</span>,
        <span itemprop="addressRegion">OH</span>
        <span itemprop="postalCode">43065</span>
      </div>
      <span itemprop="telephone">(614) 537-6728</span>
      <a href="mailto:markjlorenz@gmail.com" itemprop="email">MarkJLorenz@gmail.com</a>
      <a href="https://github.com/dapplebeforedawn" itemprop="url">On GitHub</a>
    </div>
    <div style='clear:both;'><!--annoying hack--></div>
  </div>

  <div class='separator'><hr /></div>

  <div class='experience-section'>
    <h3>Ruby on Rails Experience:</h2>
    <ul>
      <li>
        <p>Building <%= link_to "LuxeLedger", 'http://www.luxeledger.com' %> I gained a very thorough understanding of both front-end and back-end Ruby on Rails.  The back end has some very specialized routing, nested models and has_many_through relationships.  I also took advanted of the plugin architecture of Rails to build specialized plugins to handle sales tax calculation, user generated reports and build a multitenant environment using PostgreSQL schemas.<p>
        <p>The front-end of LuxeLedger taught me how to write semantic HTML, and work with AJAX loaded content.
        </p>
      </li>
      <li>
        <p>Building <%= link_to "MessagesOnAMission", 'http://build.messagesonamission.com' %> I learned how to manage complexity when sharing data with a polyglot (Node.js in this case) application addressed at a different domain.  The Rails side of MessagesOnAMission is basically just an administration and setup page, but it needed to be able to supply data to the workhorse, Node.js application that my users would be interacting with.<p>
        <p>An informed eye will notice that MessagesOnAMission relies heavily on <%= link_to "TwitterBootstrap", "http://twitter.github.com/bootstrap/" %> for markup and styling.  Using Bootstrap is a humbling experience, those gents know CSS far better than I every will. </p>
      </li>
    </ul>
  </div>

  <div class='experience-section'>
    <h3>Test Experience:</h2>
    <ul>
      <li>
        <p>
          My more recent web applications have had a strong emphasis on testing.  I use Rspec, Cucumber, Capybara and FactoryGirl to ensure that my applications work the way I want them to, even after a refactor.  
        </p>
        <p>The open source applications do not include any non-generated test code.  It's been a real learning experience to see all the unexpected ways an application can break when a new feature is added, or an existing one removed.  You could say I'm a school of hard knocks test devotee.  Since I don't have any open sourced test code, I love to talk about your situation, and how we'd spec and test it.</p>
      </li>
    </ul>
  </div>

  <div class='experience-section'>
    <h3>Node.js, Socket.io and Express.js Experience:</h2>
    <ul>
      <li>
        <p>The application side of MessagesOnAMission is written using Node.js, Socket.io and Express.js.  The use of these technologies showed me that javascript is way more than just jQuery, and in many ways is a language powerful enough to dethrone Ruby as my favorite language (well, almost) </p> 
        <p>MessagesOnAMission uses a pretty novel templating system that allows users to pick from different animations, and apply them to their presentation.  Even though the animations may have different options, and layout requirements, using my templating system I can quickly add new animations.  For example, see the "fish bowl" animation, as opposed to "movie credits" animation.  All this is done without the future-fragile need to store markup specific code in the database.</p>
      </li>
    </ul>
  </div>

  <div class='experience-section'>
    <h3>jQuery Experience:</h2>
    <ul>
      <li>
        <p>LuxeLedger would not have been possible without jQuery and the jQuery UI.  Building LuxeLedger, I learned how to effective use the UI widgets, and ended up writing several custom jQuery widgets.</p> 
        <p>LuxeLedger also takes advantage of the DOM manipulation and asyncronous javascript features of jQuery to progressively enhance the user experience.</p>
      </li>
    </ul>
  </div>

  <%= render 'mobile_experience' %>

  <%= render 'shipped_applications' %>

  <%= render 'work_and_education' %>

</div>

<script type="text/javascript">
jQuery(function($){
  $('h1').CreateBubblePopup({
    position: 'top',
    align: 'center',
    innerHtml: '<img src="/images/ajax-loader.gif" style="border:0px; vertical-align:middle; margin-right:10px; display:inline;" />loading!',
    innerHtmlStyle: { color:'#FFFFFF', 'text-align':'center' },
    selectable: true,
    themeName: 'azure',
    themePath: '/images/jquerybubblepopup-theme'
  });

  // add a mouseover event for the "button" element...
  $('h1').mouseover(function(){
    var button = $(this);
    $.get('/me.html', function(data) {
      button.SetBubblePopupInnerHtml(data, true);
    }); 
  });
});
</script>

app/views/layouts/_footer.html.erb
<div class='footer'>
  Copyright Mark J. Lorenz - Dapple Before Dawn Ltd. - 2011
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mark J. Lorenz's Resume</title>
  <%= stylesheet_link_tag :all %>
  <%#= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'jquery-1.6.1.min.js' %>
  <%= javascript_include_tag 'rails.js', 'jquery-ui-1.8.13.custom.min' %>
  <%= javascript_include_tag "jquery.bubblepopup.v2.3.1.min.js"%>
  <%= javascript_include_tag 'noisy', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <%= yield %>
  <%= render '/layouts/footer' %>
</body>
</html>